name: ci

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*.*.*'
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - 'config.example.**'
      - '**.sh'
      - '**.json'
      - '**.yml'
      - '!.github/workflows/**'

jobs:
  check:
    name: Review the code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Check
      run: cargo check

  build:
    name: Build the binary file
    if: ${{ github.event_name != 'pull_request' && success() }}
    runs-on: ubuntu-latest
    needs:
      - check
    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: |
        docker run -i --rm \
        -v $PWD:/workdir \
        -v ~/.cargo/git:/root/.cargo/git \
        -v ~/.cargo/registry:/root/.cargo/registry \
        registry.gitlab.com/rust_musl_docker/image:stable-latest \
        cargo build --profile=fast -vv --target=x86_64-unknown-linux-musl
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: biliroaming-rust-server-${{ github.run_number }}
        path: |
          ./target/x86_64-unknown-linux-musl/fast/biliroaming_rust_server
  
  alpha:
    name: Upload the Alpha test version file
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
    - uses: actions/checkout@v3

    - name: Check if alpha-releases tag exists
      id: check_tag
      run: echo ::set-output name=tag_exists::$(git tag --list "alpha-releases")
    - name: Delete old release assets
      if: steps.check_tag.outputs.tag_exists == 'alpha-releases'
      uses: mknejp/delete-release-assets@v1
      with:
        token: ${{ github.token }}
        tag: alpha-releases
        assets: |
          biliroaming_rust_server
    - name: Release
      if: steps.check_tag.outputs.tag_exists == 'alpha-releases'
      uses: softprops/action-gh-release@v1
      with:
        prerelease: true
        tag_name: alpha-releases
        files: |
          ./target/x86_64-unknown-linux-musl/fast/biliroaming_rust_server

  release:
    name: Upload the binary file when it is released
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./target/x86_64-unknown-linux-musl/fast/biliroaming_rust_server
