name: ci

on:
  push:
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - 'config.example.**'
      - '**.sh'
      - '**.json'
      - '**.yml'
      - '!.github/workflows/**'

jobs:
  check:
    name: Review the code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Check
      run: cargo check

  build:
    name: Build the binary file
    if: ${{ github.event_name != 'pull_request' && success() }}
    runs-on: ubuntu-latest
    needs:
      - check
    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: |
        docker run -i --rm \
        -v $PWD:/workdir \
        -v ~/.cargo/git:/root/.cargo/git \
        -v ~/.cargo/registry:/root/.cargo/registry \
        registry.gitlab.com/rust_musl_docker/image:stable-latest \
        cargo build --profile=fast -vv --target=x86_64-unknown-linux-musl
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: biliroaming-rust-server-${{ github.run_number }}
        path: |
          ./target/x86_64-unknown-linux-musl/fast/biliroaming_rust_server

  docker:
    name: Build Docker and Upload
    if: ${{ github.event_name != 'pull_request' && success() }}
    runs-on: ubuntu-latest
    needs:
      - check
    steps:
    - uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4.6.0
      with:
        images: ${{ secrets.DOCKER_HUB_USERNAME }}/biliroaming-rust-server
        tags: |
          type=ref,event=branch
          type=sha

    - name: Build and push Docker image
      uses: docker/build-push-action@v4.1.1
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
  
  alpha:
    name: Upload the Alpha test version file
    if: ${{ contains(github.ref, 'refs/tags/alpha-releases') }}
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
    - uses: actions/checkout@v3

    - name: Delete old release assets
      uses: mknejp/delete-release-assets@v1
      with:
        token: ${{ github.token }}
        tag: alpha-releases
        assets: |
          biliroaming_rust_server
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        prerelease: true
        tag_name: alpha-releases
        files: |
          ./target/x86_64-unknown-linux-musl/fast/biliroaming_rust_server

  release:
    name: Upload the binary file when it is released
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./target/x86_64-unknown-linux-musl/fast/biliroaming_rust_server
